from django.conf.urls import url 
from rango import views

urlpatterns = [ 
    url(r'^$', views.index, name='index'),
    url(r'^search/$', views.search, name='search'),
    url(r'^suggest/$', views.suggest_category, name='suggest_category'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',
        views.show_category, name='show_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$',
        views.add_page, name='add_page'),
    url(r'^register/$', views.register,name='register'),
    url(r'^login/$', views.user_login, name='login'),  
    url(r'^restricted/', views.restricted, name='restricted'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^gamereview/$', views.gamereview, name='gamereview'),
    url(r'^gamereview2/$', views.gamereview2, name='gamereview2'),
    url(r'^gamereview3/$', views.gamereview3, name='gamereview3'),
    url(r'^adultgamereview/$', views.adultgamereview, name='adultgamereview'),
    url(r'^gamenews/$', views.gamenews, name='gamenews'),
    url(r'^deadbydaylightnews/$', views.deadbydaylightnews, name='deadbydaylightnews'),
    url(r'^conanexiles/$', views.conanexilesnews, name='cononexilesnews'),
    url(r'^ps4news/$', views.ps4news, name='ps4news'),
    url(r'^marionews/$', views.marionews, name='marionews'),
    url(r'^adultgamenews/$', views.adultgamenews, name='adultgamenews'),
    url(r'^senrankaguraburstrenewal/$', views.senrankaguraburstrenewal, name='senrankaguraburstrenewal'),
    url(r'^gta6news/$', views.gta6news, name='gta6news'),
    url(r'^deadoralive6news/$', views.deadoralivenews, name='deadoralive6news'),
    url(r'goto/$', views.track_url, name='goto'),
    url(r'^register_profile/$', views.register_profile, name='register_profile'),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name='profile'),
    url(r'^profiles/$', views.list_profiles, name='list_profiles'),
    url(r'^like/$', views.like_category, name='like_category'),
]
