# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20190312_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='introduction',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='category',
            name='review',
            field=models.CharField(max_length=65536),
        ),
    ]
