# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20190312_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='yturl',
            field=models.CharField(max_length=128),
        ),
    ]
